const mongoose = require("mongoose");

const socialPostSchema = new mongoose.Schema(
  {
    platform: {
      type: String,
      required: true,
      enum: ["instagram", "facebook", "twitter", "youtube"],
      lowercase: true,
      trim: true,
      index: true,
    },
    postId: {
      type: String,
      required: true,
      trim: true,
      index: true,
    },
    title: {
      type: String,
      trim: true,
      maxlength: 300,
      default: "",
    },
    caption: {
      type: String,
      trim: true,
      maxlength: 5000,
      default: "",
    },
    url: {
      type: String,
      trim: true,
      required: true,
      maxlength: 1000,
    },
    mediaType: {
      type: String,
      enum: ["image", "video", "carousel", "text"],
      default: "image",
    },
    mediaUrl: {
      type: String,
      trim: true,
      default: "",
    },
    thumbnailUrl: {
      type: String,
      trim: true,
      default: "",
    },
    embedHtml: {
      type: String,
      default: "",
    },
    author: {
      name: {
        type: String,
        trim: true,
        default: "निषाद आरक्षण संकल्प",
      },
      username: {
        type: String,
        trim: true,
        default: "nishadsankalp",
      },
      avatarUrl: {
        type: String,
        trim: true,
        default: "/images/logo.png",
      },
      profileUrl: {
        type: String,
        trim: true,
        default: "https://www.instagram.com",
      },
    },
    publishedAt: {
      type: Date,
      default: Date.now,
      index: true,
    },
    formattedDate: {
      type: String,
      default: "",
    },
    likesCount: {
      type: Number,
      default: 0,
      min: 0,
    },
    commentsCount: {
      type: Number,
      default: 0,
      min: 0,
    },
    sharesCount: {
      type: Number,
      default: 0,
      min: 0,
    },
    viewsCount: {
      type: Number,
      default: 0,
      min: 0,
    },
    tags: [
      {
        type: String,
        trim: true,
      },
    ],
    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },
    isPinned: {
      type: Boolean,
      default: false,
      index: true,
    },
    rawMetadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
  },
  {
    timestamps: true,
  }
);

socialPostSchema.index({ platform: 1, isActive: 1, publishedAt: -1 });
socialPostSchema.index({ isActive: 1, isPinned: -1, publishedAt: -1 });
socialPostSchema.index({ postId: 1, platform: 1 }, { unique: true });

socialPostSchema.statics.defaultPosts = [
  // ================= INSTAGRAM POSTS =================
  {
    platform: "instagram",
    postId: "ig-001",
    title: "ऐतिहासिक कलश यात्रा का जनसैलाब",
    caption: "वाराणसी में आयोजित भव्य कलश यात्रा में हज़ारों युवाओं और माताओं-बहनों ने लिया भाग। आरक्षण और सम्मान के लिए एकजुटता का संकल्प!",
    url: "https://www.instagram.com/p/DFkalash01/",
    mediaType: "video",
    mediaUrl: "/images/kalash-yatra-featured.jpg",
    thumbnailUrl: "/images/kalash-yatra-featured.jpg",
    publishedAt: new Date("2026-05-25T14:30:00Z"),
    formattedDate: "25 May 2026",
    likesCount: 14301,
    commentsCount: 751,
    sharesCount: 3120,
    tags: ["NishadSankalp", "KalashYatra", "Varanasi"],
    isActive: true,
  },
  {
    platform: "instagram",
    postId: "ig-002",
    title: "युवा शक्ति, देश की शक्ति",
    caption: "पटना में छात्र एवं युवा सम्मेलन में उमड़ा उत्साह। शिक्षा के क्षेत्र में नई राहें खोलने और समाज के हर बच्चे तक उत्तम शिक्षा पहुँचाने का संकल्प।",
    url: "https://www.instagram.com/p/DFpatna02/",
    mediaType: "video",
    mediaUrl: "/images/democratic-pledge-patna.jpg",
    thumbnailUrl: "/images/democratic-pledge-patna.jpg",
    publishedAt: new Date("2026-05-24T11:15:00Z"),
    formattedDate: "24 May 2026",
    likesCount: 119735,
    commentsCount: 2152,
    sharesCount: 12400,
    tags: ["YuvaShakti", "Patna", "Education"],
    isActive: true,
  },
  {
    platform: "instagram",
    postId: "ig-003",
    title: "पवित्र गंगा घाट पर संकल्प आरती",
    caption: "पूरे देश में सामाजिक न्याय और अधिकारों की माँग को लेकर गंगा घाट पर सामूहिक दीप प्रज्वलन एवं ऐतिहासिक संकल्प।",
    url: "https://www.instagram.com/p/DFghat03/",
    mediaType: "video",
    mediaUrl: "/images/ghat-kalash-procession.jpg",
    thumbnailUrl: "/images/ghat-kalash-procession.jpg",
    publishedAt: new Date("2026-05-23T18:40:00Z"),
    formattedDate: "23 May 2026",
    likesCount: 76182,
    commentsCount: 4934,
    sharesCount: 8900,
    tags: ["GangaGhat", "Sankalp", "Aarti"],
    isActive: true,
  },
  {
    platform: "instagram",
    postId: "ig-004",
    title: "लोकतांत्रिक जन जागरण यात्रा",
    caption: "देश के कई हिस्सों में जन जागरण यात्रा को मिल रहा है अपार जनसमर्थन। अपने हक और अधिकार के प्रति जागरूक हो रहा है समाज।",
    url: "https://www.instagram.com/p/DFranchi04/",
    mediaType: "image",
    mediaUrl: "/images/ranchi-kalash-procession.jpg",
    thumbnailUrl: "/images/ranchi-kalash-procession.jpg",
    publishedAt: new Date("2026-05-22T09:20:00Z"),
    formattedDate: "22 May 2026",
    likesCount: 10308,
    commentsCount: 655,
    sharesCount: 1420,
    tags: ["Ranchi", "Jharkhand", "JanJagran"],
    isActive: true,
  },
  {
    platform: "instagram",
    postId: "ig-005",
    title: "महिलाओं की ऐतिहासिक भागीदारी",
    caption: "मातृशक्ति के सहयोग से ही किसी भी बड़े सामाजिक आंदोलन को विजय मिलती है। निषाद आरक्षण संकल्प में महिलाओं का अभूतपूर्व समर्थन।",
    url: "https://www.instagram.com/p/DFwomen05/",
    mediaType: "video",
    mediaUrl: "/images/sacred-kalash-ritual.jpg",
    thumbnailUrl: "/images/sacred-kalash-ritual.jpg",
    publishedAt: new Date("2026-05-21T16:00:00Z"),
    formattedDate: "21 May 2026",
    likesCount: 45210,
    commentsCount: 1820,
    sharesCount: 5610,
    tags: ["MatruShakti", "Empowerment", "Women"],
    isActive: true,
  },

  // ================= FACEBOOK POSTS =================
  {
    platform: "facebook",
    postId: "fb-001",
    title: "प्रयागराज में विशाल जनचौपाल संपन्न",
    caption: "प्रयागराज की धरती पर समाज के हज़ारों नागरिकों के साथ संवाद। जब तक हमें हमारा संवैधानिक हक नहीं मिलता, हमारा लोकतांत्रिक संघर्ष अनवरत जारी रहेगा।",
    url: "https://www.facebook.com/nishadsankalp/posts/101",
    mediaType: "image",
    mediaUrl: "/images/democratic-pledge-featured.jpg",
    thumbnailUrl: "/images/democratic-pledge-featured.jpg",
    publishedAt: new Date("2026-05-25T13:00:00Z"),
    formattedDate: "25 May 2026",
    likesCount: 38450,
    commentsCount: 1420,
    sharesCount: 4890,
    tags: ["Prayagraj", "JanChaupal", "Rights"],
    isActive: true,
  },
  {
    platform: "facebook",
    postId: "fb-002",
    title: "मध्य प्रदेश के भोपाल में प्रतिनिधि बैठक",
    caption: "भोपाल में विभिन्न ज़िलों से आए कार्यकर्ताओं एवं समाजसेवियों के साथ आगामी रणनीति पर विस्तृत चर्चा की गई। सामाजिक एकता ही हमारी असली पहचान है।",
    url: "https://www.facebook.com/nishadsankalp/posts/102",
    mediaType: "image",
    mediaUrl: "/images/democratic-pledge-bhopal.jpg",
    thumbnailUrl: "/images/democratic-pledge-bhopal.jpg",
    publishedAt: new Date("2026-05-24T17:45:00Z"),
    formattedDate: "24 May 2026",
    likesCount: 24190,
    commentsCount: 960,
    sharesCount: 2310,
    tags: ["Bhopal", "Strategy", "Unity"],
    isActive: true,
  },
  {
    platform: "facebook",
    postId: "fb-003",
    title: "गाँव-गाँव में चौपाल और संकल्प पत्र वितरण",
    caption: "हर पंचायत और हर गाँव में संकल्प पत्र पहुँचाने का लक्ष्य। शिक्षा, आरक्षण और युवाओं के रोज़गार के सवाल पर कोई समझौता नहीं होगा।",
    url: "https://www.facebook.com/nishadsankalp/posts/103",
    mediaType: "image",
    mediaUrl: "/images/democratic-pledge-varanasi.jpg",
    thumbnailUrl: "/images/democratic-pledge-varanasi.jpg",
    publishedAt: new Date("2026-05-23T12:30:00Z"),
    formattedDate: "23 May 2026",
    likesCount: 18720,
    commentsCount: 680,
    sharesCount: 1890,
    tags: ["Panchayat", "SankalpPatra", "GroundReport"],
    isActive: true,
  },
  {
    platform: "facebook",
    postId: "fb-004",
    title: "छात्रों एवं नौजवानों का महासम्मेलन",
    caption: "नौजवानों ने ली शपथ: हम शिक्षित बनेंगे, संगठित होंगे और अपने अधिकारों के लिए संवैधानिक मार्ग पर चलकर इतिहास रचेंगे।",
    url: "https://www.facebook.com/nishadsankalp/posts/104",
    mediaType: "image",
    mediaUrl: "/images/democratic-pledge-patna.jpg",
    thumbnailUrl: "/images/democratic-pledge-patna.jpg",
    publishedAt: new Date("2026-05-22T10:10:00Z"),
    formattedDate: "22 May 2026",
    likesCount: 14500,
    commentsCount: 512,
    sharesCount: 1340,
    tags: ["YouthConference", "Students", "Future"],
    isActive: true,
  },

  // ================= TWITTER / X POSTS =================
  {
    platform: "twitter",
    postId: "tw-001",
    title: "RT @BhagwantMann: Punjab government will strictly follow",
    caption: "RT @BhagwantMann: Punjab government will strictly follow in letter and spirit the Supreme Court order given on 19th May 2026. As per the SC...",
    url: "https://twitter.com/nishadsankalp/status/1780001",
    mediaType: "text",
    publishedAt: new Date("2026-05-22T08:00:00Z"),
    formattedDate: "22 May 2026",
    likesCount: 0,
    commentsCount: 0,
    sharesCount: 332,
    tags: ["SC", "Order", "News"],
    isActive: true,
  },
  {
    platform: "twitter",
    postId: "tw-002",
    title: "राजा राममोहन राय जी की जयंती पर नमन",
    caption: "हमारे समाज को एक नई और प्रगतिशील दिशा देने वाले राजा राममोहन राय जी की जयंती पर उन्हें कोटि-कोटि नमन। उनके द्वारा शिक्षा व्यवस्था में किए गए सुधार हमें आज भी प्रेरित करते हैं कि हम देश के हर एक बच्चे तक बिना ...",
    url: "https://twitter.com/nishadsankalp/status/1780002",
    mediaType: "text",
    publishedAt: new Date("2026-05-22T06:30:00Z"),
    formattedDate: "22 May 2026",
    likesCount: 2985,
    commentsCount: 349,
    sharesCount: 2167,
    tags: ["Tribute", "Education", "Reform"],
    isActive: true,
  },
  {
    platform: "twitter",
    postId: "tw-003",
    title: "देश के कई हिस्सों में ऐसे हालात देखने को मिल रहे हैं",
    caption: "देश के कई हिस्सों में ऐसे हालात देखने को मिल रहे हैं। सरकार कुछ नहीं बता रही - तेल और गैस का सरकार के पास कितना स्टॉक है और वो कितने दिन चलेगा? और कितना स्टॉक कब आने की उम्मीद है? चारों तरफ़ अफ़वाहों का बाज़ार गर्म है। चारों तरफ़ अफ़रा तफ़री है। सरकार...",
    url: "https://twitter.com/nishadsankalp/status/1780003",
    mediaType: "text",
    publishedAt: new Date("2026-05-22T05:15:00Z"),
    formattedDate: "22 May 2026",
    likesCount: 4489,
    commentsCount: 457,
    sharesCount: 1928,
    tags: ["Questions", "PublicInterest", "GroundReality"],
    isActive: true,
  },
  {
    platform: "twitter",
    postId: "tw-004",
    title: "देश के पूर्व प्रधानमंत्री श्री राजीव गांधी जी की पुण्यतिथि",
    caption: "देश के पूर्व प्रधानमंत्री श्री राजीव गांधी जी की पुण्यतिथि पर विनम्र श्रद्धांजलि। आधुनिक भारत के निर्माण और युवाओं को 18 वर्ष में मताधिकार देने में उनका योगदान सदैव स्मरणीय रहेगा।",
    url: "https://twitter.com/nishadsankalp/status/1780004",
    mediaType: "text",
    publishedAt: new Date("2026-05-21T09:00:00Z"),
    formattedDate: "21 May 2026",
    likesCount: 6109,
    commentsCount: 527,
    sharesCount: 2300,
    tags: ["Homage", "Democracy", "VotingRights"],
    isActive: true,
  },
  {
    platform: "twitter",
    postId: "tw-005",
    title: "शिक्षा और रोज़गार: हमारा संकल्प",
    caption: "जब तक निषाद समाज के हर युवा के हाथ में रोज़गार और हर बच्चे के हाथ में क़लम नहीं होगी, तब तक यह महा-अभियान नहीं थमेगा। एकजुट हों, अधिकार मांगें! ✊🌊 #NishadReservation",
    url: "https://twitter.com/nishadsankalp/status/1780005",
    mediaType: "text",
    publishedAt: new Date("2026-05-20T14:20:00Z"),
    formattedDate: "20 May 2026",
    likesCount: 5120,
    commentsCount: 380,
    sharesCount: 1840,
    tags: ["NishadReservation", "YouthPower"],
    isActive: true,
  },
];

module.exports = mongoose.models.SocialPost || mongoose.model("SocialPost", socialPostSchema);
